### ISSUE TITLE
Code generation and RXQueryExecutor mismatch

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#104]
jOOQ version: 3.11.9
vert-jooq version: 4.1.0

I'm looking at the generated DAOs and notice that the constructor, as shown below, refers to the `JDBCRXQueryExecutor`

```java
    public AddressDao(Configuration configuration, io.vertx.reactivex.core.Vertx vertx) {
        super(AddressTable.ADDRESS, Address.class, new JDBCRXQueryExecutor<AddressRecord,Address,UUID>(configuration,Address.class,vertx));
    }
```

However, I want to specify that the `ReactiveRXGenericQueryExecutor` be used instead as the run time code relies on it. I looked through the documentation and did not find any jOOQ code generation settings to enable this scenario. How can I do it?

**Comment by paninics** [comment]
I was able to figure it out. My custom code generator extended `RXJDBCVertxGenerator` instead of `RXReactiveVertxGenerator`. But now, I run into a possible bug as I get the below exception.

```java
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.github.jklingsporn.vertx.jooq.generate.builder.VertxGeneratorBuilder$ExecutionStepImpl.lambda$withPostgresReactiveDriver$30(VertxGeneratorBuilder.java:411)
	at io.github.jklingsporn.vertx.jooq.generate.builder.ComponentBasedVertxGenerator.writeDAOConstructor(ComponentBasedVertxGenerator.java:83)
	at io.github.jklingsporn.vertx.jooq.generate.builder.DelegatingVertxGenerator.writeDAOConstructor(DelegatingVertxGenerator.java:64)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDAO(VertxGenerator.java:564)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDao(VertxGenerator.java:501)
	at org.jooq.codegen.JavaGenerator.generateDao(JavaGenerator.java:2867)
	at org.jooq.codegen.JavaGenerator.generateDaos(JavaGenerator.java:2854)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDaos(VertxGenerator.java:234)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:512)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:458)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:380)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:752)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:222)
```

Upon debugging, it appears that the [code in VertxGeneratorBuilder](https://github.com/jklingsporn/vertx-jooq/blob/0db00b5e040639c309691dfbc125034fa3346d88/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/builder/VertxGeneratorBuilder.java#L411) is making assumptions about the path / package name space that is incorrect.

**Comment by paninics** [comment]
And here's a simple way to reproduce the problem. Use a custom code generator strategy, shown below, along with `RXReactiveVertxGenerator`.
```java
public class TestGeneratorStrategy extends VertxGeneratorStrategy {

    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        String s = super.getJavaClassName(definition, mode);
        if (mode == Mode.DEFAULT && definition instanceof TableDefinition) {
            s = s + "Table";
        }
        return s;
    }
}
```

The issue has something to do with `Mode.DEFAULT` as if we remove the partial check (i.e. `mode == Mode.DEFAULT`) in the above if clause, we would no longer get the error. Also to be noted, if we switch to using `RXJDBCVertxGenerator` along with the above code generator strategy as is, it works!

**Comment by paninics** [comment]
Upon further experimenting, it appears that the generation code is expecting the class names for the `pojo` and `table` objects to be the same. Below is a slight variation to the custom code generator strategy to demonstrate that you would no longer get the error, though of course the `pojo` class names does not make sense in this example. In summary, we need these names to be decoupled. 

```java
public class TestGeneratorStrategy extends VertxGeneratorStrategy {
    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        String s = super.getJavaClassName(definition, mode);
        if (mode == Mode.DEFAULT && definition instanceof TableDefinition) {
            s = s + "Table";
        } else if (mode == Mode.POJO) {
            s = s + "Table";
        }
        return s;
    }
}
```
