### ISSUE TITLE
Showcase with vertx-mysql-postgresql-client

### ISSUE THREAD

**Issue by jklingsporn** [jklingsporn/vertx-jooq#11]
See if we can add a module that uses the 'real' async sql driver.

**Comment by jklingsporn** [comment]
Unfortunately I have an issue with the async-library. When I test my code it throws the following error:
```
java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2ab6 0057 04a0 001e b200 afb2 00b4 04bd
    0000010: 0002 5903 2a53 c000 b6b6 00ba b600 bec0
    0000020: 00c0 b02a b600 31b8 003b 3c1b 04a4 015e
    0000030: 1b05 6c3d 2a1b 056c 2ab6 0031 b700 c23e
    0000040: 2ab6 0031 021d 787e 3604 2ab6 0031 0210
    0000050: 201d 647c 7e36 05bb 0014 59b2 00b4 2ab6
    0000060: 0033 c000 b6b6 00c6 b700 c91c b600 cd3a
    0000070: 0619 06c6 001a 1906 b600 d1c0 007d 3a07
    0000080: 1906 b600 d4c0 007d 3a08 a700 0dbb 00d6
    0000090: 5919 06b7 00d9 bf19 073a 0919 083a 0abb
    00000a0: 0002 5915 0419 09bb 0014 59b2 00b4 1909
    00000b0: c000 b6b6 00c6 b700 c903 b800 df3a 0e3a
    00000c0: 0d03 190d b900 e301 0019 0e3a 1136 1036
    00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    00000e0: 150f b900 e602 00c0 0005 3a17 1911 1917
    00000f0: b800 ea3a 1136 1036 0fa7 ffd8 1911 b800
    0000100: eeb7 005c 3a0b bb00 0259 1505 190a bb00
    0000110: 1459 b200 b419 0ac0 00b6 b600 c6b7 00c9
    0000120: 03b8 00df 3a13 3a12 0319 12b9 00e3 0100
    0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0000140: 1404 6015 1519 1215 14b9 00e6 0200 c000
    0000150: 053a 1819 1619 18b8 00f1 3a16 3615 3614
    0000160: a7ff d819 16b8 00ee b700 5c3a 0cb2 00f6
    0000170: b200 b405 bd00 0259 0319 0b53 5904 190c
    0000180: 53c0 00b6 b600 bab6 00f9 b02a b600 3303
    0000190: 32b6 00fb b0                           
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105]},{})
    append_frame(@151,Object[#125],Object[#125])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Top,Top,Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#125]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#105],Object[#125],Object[#125],Object[#125],Object[#125],Object[#2],Top,Object[#20],Object[#55],Integer,Integer,Object[#103],Object[#20],Object[#55],Integer,Integer,Object[#103]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#125]})
    full_frame(@395,{Object[#2],Integer},{})

	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:179)
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:211)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:59)
	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:201)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:202)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:317)
	at scala.collection.TraversableOnce$$Lambda$17/953082513.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:316)
	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:314)
	at scala.collection.AbstractTraversable.toMap(Traversable.scala:104)
	at scala.concurrent.duration.Duration$.<init>(Duration.scala:88)
	at scala.concurrent.duration.Duration$.<clinit>(Duration.scala)
	at scala.concurrent.duration.Duration.apply(Duration.scala)
	at io.vertx.ext.asyncsql.impl.BaseSQLClient.getConfiguration(BaseSQLClient.java:131)
	at io.vertx.ext.asyncsql.impl.MYSQLClientImpl.<init>(MYSQLClientImpl.java:40)
	at io.vertx.ext.asyncsql.impl.AsyncSQLClientImpl.<init>(AsyncSQLClientImpl.java:35)
	at io.vertx.ext.asyncsql.impl.ClientHolder.client(ClientHolder.java:48)
	at io.vertx.ext.asyncsql.impl.ClientWrapper.<init>(ClientWrapper.java:36)
	at io.vertx.ext.asyncsql.impl.ClientHelper.getOrCreate(ClientHelper.java:47)
	at io.vertx.ext.asyncsql.MySQLClient.createNonShared(MySQLClient.java:89)
	at io.github.jklingsporn.vertx.jooq.generate.future.async.VertxAsyncDaoTestBase.beforeClass(VertxAsyncDaoTestBase.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
I've googled around a bit and found that this problem can be related to an old Java 8 version. Although I'm running build 1.8.0-b132 now, the problem still exists. Any ideas?

**Comment by vietj** [comment]
that looks scarry

**Comment by jklingsporn** [comment]
So I've created a simple maven project that does only one thing
```
public static void main(String[] args) {
        JsonObject config = new JsonObject().put("host", "127.0.0.1").put("user", "vertx").put("password", "").put("database","vertx");
        MySQLClient.createNonShared(Vertx.vertx(), config);
    }
```
And it fails with the same error. Here is my pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.jklingsporn</groupId>
    <artifactId>async-sql-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>3.4.1</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mysql-postgresql-client</artifactId>
            <version>3.4.1</version>
        </dependency>
    </dependencies>

</project>
```
I'm running this on a MacBook with this Java-Version
```
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
```
Do I need to have other dependencies installed, e.g. scala?

**Comment by jklingsporn** [comment]
Linked to https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/80
Created reproducer: https://github.com/jklingsporn/async-sql-test

**Comment by jklingsporn** [comment]
Fixed. I referenced a wrong Java installation inside IntelliJ.

**Comment by jklingsporn** [comment]
See https://github.com/jklingsporn/vertx-jooq-async/
