### ISSUE TITLE
Support postgres bytea type in the reactive driver

### ISSUE THREAD

**Issue by gtejasvi** [jklingsporn/vertx-jooq#153]
Insert of Column with bytea fails with the following error:

```
io.vertx.pgclient.PgException: invalid byte sequence for encoding "UTF8": 0x00
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
	at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:235)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:123)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:103)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

This behaviour is observed in either cases when the value is actully null and also when it is not null. I am currently using a Convertor to convert the byte to Buffer. But the same error is observed even without the convertor.

**Comment by jklingsporn** [comment]
Hi and sorry for my late reply. 
I've added a `bytea`-column to my test cases and still everything works. Can you share some more information on the issues you're having?

**Comment by jklingsporn** [comment]
I figured out that `bytea` is ignored by the `RowMappers`. Fix incoming.
