### ISSUE TITLE
Receiving exception "The number of values must match the number of fields" when inserting Collection of Records in intermediary table using Transaction

### ISSUE THREAD

**Issue by nixos89** [jklingsporn/vertx-jooq#154]
Hi,
I have problem with performing insert of Collection of Records in INSERT statement in **_InsertValuesStep2<R,T1,T2> values(Collection<?> values)_** method and exception that I am receiving is occurring at [this line](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/f50d4f1cd28b2edc9bc5aa8888f8b80ffa2cfb03/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/service/BookServiceImpl.java#L184) in mentioned method. After performing Http POST request (to SAVE book) I am receiving following exception:
```
java.lang.IllegalArgumentException: The number of values must match the number of fields
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:309)
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:324)
	at org.jooq.impl.InsertImpl.values(InsertImpl.java:126)
	at com.ns.vertx.pg.service.BookServiceImpl.lambda$11(BookServiceImpl.java:184)
	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractQueryExecutor.createQuery(AbstractQueryExecutor.java:38)
	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.executeAny(ReactiveClassicGenericQueryExecutor.java:145)
	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.execute(ReactiveClassicGenericQueryExecutor.java:58)
	at com.ns.vertx.pg.service.BookServiceImpl.lambda$8(BookServiceImpl.java:181)
```

Since I had to re-factor my code (from [this](https://github.com/jklingsporn/vertx-jooq/issues/150) issue) NOT to use DAO classes in order to be able to use TRANSACTIONS I am having problem when I need to insert Author and Category IDs (from JSON Request Body), that is records in intermediary tables for Many-To-Many relationship. 
Because _values()_ needs to accept  Collection I have created List of _**AuthorBookRecord/CategoryBookRecord**_ which I have extracted from JSON Body Request. As matter of using transactions I've used [transaction(..)](https://github.com/jklingsporn/vertx-jooq/blob/f742231872ecd300962e4c730ef62c596beef975/vertx-jooq-classic-reactive/src/main/java/io/github/jklingsporn/vertx/jooq/classic/reactivepg/ReactiveClassicGenericQueryExecutor.java#L132) convenience method in order to simplify code readability and commented out queryExecutor.rollback() method on lines 197-199 in createBookJooq method so I can get stack-trace to see where exception occurs - if it's UNCOMMENTED than it doesn't show (stack-trace).

Also, I've researched through jOOQ documentation (batchInsert() and insertInto() methods), Stackoverflow and Google Groups about performing multiple value inserts which are using execute() or fetch() method, but nothing seems to fit my use-case since (if I recall correctly) Vertx-jOOQ does NOT support last mentioned methods. I guess I am not passing Collection (of Author/CategoryBookRecord instances) created the right way or is it something entirely else that is causing this exception?
Thank you in advance.

**P.S.** I am using **vertx-jooq-classic-reactive 5.1.1** and **vertx 3.9** and code for mentioned issue is on [05-implement-transactions](https://github.com/nixos89/VertxPgReactiveJOOQ/tree/05-implement-transactions/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/service) branch.

**Comment by nixos89** [comment]
After taking longer break and coming back to resolve this issue I've managed to find a solution to this problem which was to create jOOQ query using CTE with help of CommonTableExpression and dsl.with(cteIdentifierName) to insert multiple category/author IDs and single book ID. So now it looks something like this:
```
CommonTableExpression<Record2<Long, Long>> category_book_tbl = DSL.name("category_book_tbl")
.fields("book_id", "category_id").as(dsl.select(BOOK.BOOK_ID,CATEGORY.CATEGORY_ID)
.from(BOOK).crossJoin(CATEGORY).where(BOOK.BOOK_ID.eq(bookId).and(CATEGORY.CATEGORY_ID.in(categoryIds)) ));
```
...that's code where I create CTE and use this to perform insertion:
```
dsl.with(category_book_tbl)
.insertInto(CATEGORY_BOOK, CATEGORY_BOOK.BOOK_ID,CATEGORY_BOOK.CATEGORY_ID)
.select(dsl.selectFrom(category_book_tbl));
```
Also, I've switched to using beginTransaction() method instead of convenience transaction(..) method for more effective debugging. Now everything works smoothly. :)
Cheers!
