### ISSUE TITLE
Recieving "SEVERE: Failed to handleMessage. address: category.queue" when working with Service Proxy classes in vertx-jooq-classic-reactive 5.1.1

### ISSUE THREAD

**Issue by nixos89** [jklingsporn/vertx-jooq#156]
I'm having issue once I generate **Service Proxy classes** (following [this](https://vertx.io/docs/guide-for-java-devs/#_refactoring_to_vert_x_services) example for my project at [this](https://github.com/nixos89/VertxPgReactiveJOOQ/tree/06-create-service-proxies/vertx-pg-reactive-jooq/src/main) repo) and try to use them in my Vert.X project to perform HTTP Get request I get following (stacktrace) error:

```
14:58:34.765 [vert.x-eventloop-thread-5] DEBUG io.netty.handler.codec.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibDecoder: false
14:58:34.765 [vert.x-eventloop-thread-5] DEBUG io.netty.handler.codec.compression.ZlibCodecFactory - -Dio.netty.noJdkZlibEncoder: false
(RECIPIENT_FAILURE,500) 
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:146)
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:53)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:276)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:262)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:572)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$4(EventBusImpl.java:531)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Jun 09, 2020 2:58:34 PM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage. address: category.queue
java.lang.NullPointerException
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:123)
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:53)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:276)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:262)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:572)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$4(EventBusImpl.java:531)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Jun 09, 2020 2:58:34 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:123)
	at com.ns.vertx.pg.service.CategoryServiceVertxProxyHandler.handle(CategoryServiceVertxProxyHandler.java:53)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:276)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:262)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:572)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$4(EventBusImpl.java:531)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```
This is part of line 123 in generated _**CategoryServiceVertxProxyHandler**_ class

```
service.getCategoryByIdJooqSP(json.getValue("id") == null ? null : (json.getLong("id").longValue()),
                        HelperUtils.createHandler(msg));
```
BTW, I'm creating instance of **ReactiveClassicGenericQueryExecutor** inside of _CategoryServiceImpl_ class constructor and using it to perform jOOQ queries and use ```category.queue``` address for messages to be passed in [HttpServerVerticle](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/06-create-service-proxies/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/http/HttpServerVerticle.java) and [DatabaseVerticle](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/06-create-service-proxies/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/service/DatabaseVerticle.java). Is there something I am missing in this whole setup and what could it be (any advice or pointing into right direction to solving this problem is welcome)?

**Versions** of libraries I'm using in my project are:
**Vert.X 3.9**
**vertx-jooq-classic-reactive 5.1.1**
**jooq-codegen-maven 3.13.1**

**Comment by nixos89** [comment]
BTW, for debugging of mentioned **line 123** I've printed out ```json.getValue("id")``` value in console and it gives **proper-passed** value.
