### ISSUE TITLE
PostgreSQL Name Case Issues When Generating Using JPADatabase

### ISSUE THREAD

**Issue by InfoSec812** [jklingsporn/vertx-jooq#189]
I am generating jOOQ DAOs using JPADatabase in my [example project](https://github.com/redhat-appdev-practice/vertx-openapi-jooq-multimodule)

For some reason, when I try to create a new row/record using the DAO's `insertReturningPrimary` method, I get the following error:

```
09:00:20.253 [vert.x-eventloop-thread-1] ERROR com.redhat.runtimes.services.TodosServiceImpl - Column ID does not exist
java.util.NoSuchElementException: Column ID does not exist
	at io.vertx.sqlclient.Row.getValue(Row.java:65) ~[vertx-sql-client-4.1.4.jar:4.1.4]
	at io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO.lambda$generatePostgresKeyConverter$1(AbstractReactiveVertxDAO.java:49) ~[vertx-jooq-shared-reactive-6.3.0.jar:?]
```

I have tried tweaking the `Configuration` to change how names/fields/schemas are rendered with respect to letter case, but it's pretty hit and miss (Mostly miss) so far. In my database, the column is `id` (lower case) and when jOOQ attempts to fetch the column is it asking for `ID` (upper case) at `io.vertx.sqlclient.Row.getValue(Row.java:65)` at which point it fails. 

Any advice? If you would like to run the example project:

1. Clone the [repository](https://github.com/redhat-appdev-practice/vertx-openapi-jooq-multimodule)
1. Switch to the `Issue-7-_-Debug_createTodo_operation` branch: `git checkout Issue-7-_-Debug_createTodo_operation`
1. Compile the code `mvn clean compile`
1. Start the PostgreSQL Container (this uses a generated DDL script from the models module, so you MUST compile first) using `docker-compose up` in the root of the project
1. Run the Vert.x application using `mvn -pl modules/api clean compile vertx:run`
1. Access the [Swagger UI](http://localhost:8080/swagger/)
1. Attempt to create a new Todo item using Swagger UI

**Comment by InfoSec812** [comment]
Hmmm... Some more information... The actual insertion of the data in the table is successful, it is just the returning of the ID field which causes a problem.
