### ISSUE TITLE
Enum type cannot be used in async driver

### ISSUE THREAD

**Issue by jklingsporn** [jklingsporn/vertx-jooq#32]
Scala does not know how to handle the enum type so it has to be converted into a String.

```
cala.MatchError: ACTIVE (of class com.actility.thingpark.enterprise.channel.portal.storage.enums.ChannelStatus)
	at com.github.mauricio.async.db.mysql.binary.BinaryRowEncoder.encoderFor(BinaryRowEncoder.scala:88) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.encoder.PreparedStatementExecuteEncoder.encodeValue(PreparedStatementExecuteEncoder.scala:78) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.encoder.PreparedStatementExecuteEncoder.encodeValues(PreparedStatementExecuteEncoder.scala:61) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.encoder.PreparedStatementExecuteEncoder.encode(PreparedStatementExecuteEncoder.scala:39) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.codec.MySQLOneToOneEncoder.encode(MySQLOneToOneEncoder.scala:75) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at com.github.mauricio.async.db.mysql.codec.MySQLOneToOneEncoder.encode(MySQLOneToOneEncoder.scala:35) ~[mysql-async_2.12-0.2.21.jar:0.2.21]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	... 35 more
```

**Comment by quen2404** [comment]
Another information about this: insertion works but not update.

**Comment by jklingsporn** [comment]
Can you try https://github.com/jklingsporn/vertx-jooq/tree/3.0.1 and see if it fixes the issues for you?

**Comment by quen2404** [comment]
Impossible to compile on my computer. Some classes are missing:
```
generated.classic.async.guice.enums.SomethingSomeenum;
generated.classic.async.regular.enums.SomethingSomeenum;
generated.rx.async.guice.enums.SomethingSomeenum;
generated.rx.async.regular.enums.SomethingSomeenum;
generated.cf.async.guice.enums.SomethingSomeenum;
generated.cf.async.regular.enums.SomethingSomeenum;
```

**Comment by jklingsporn** [comment]
Sorry, forgot to add them to git. Please try again.

**Comment by quen2404** [comment]
No problem ! 
Compilation... **OK**
Runtime... **OK** 
It works perfectly ! Thank you, you rock!
