### ISSUE TITLE
Error converting binary(16) to String using custom converter

### ISSUE THREAD

**Issue by zeroc** [jklingsporn/vertx-jooq#55]
Hello,

Thanks for making this awesome project for vertx.
I'm currently using vertx-jooq-completablefuture-async and vertx-mysql-postgresql-client to talk to mysql 5.7
**I wanted to use UUID in binary(16) form as primary key, so I wrote a simple custom converter as following:**

public class UUIDConverter implements Converter<byte[], String> {

	private static final long serialVersionUID = 5799037733019312285L;

	@Override
    public String from(byte[] databaseObject) {
        return databaseObject == null ? null : UUID.toStringId(databaseObject);
    }

    @Override
    public byte[] to(String userObject) {
        return userObject == null ? null : UUID.toBinaryId(userObject);
    }

    @Override
    public Class<byte[]> fromType() {
        return byte[].class;
    }

    @Override
    public Class<String> toType() {
        return String.class;
    }
}
public class UUID {
    public static byte[] toBinaryId(String strId) {
    	byte[] src = new byte[16];
    	byte[] uuidBytes = new byte[16];
		try {
			src = Hex.decodeHex(strId.replaceAll("-", ""));
	    	ByteBuffer.wrap(uuidBytes)
				.put(src, 6, 2)
				.put(src, 4, 2)
				.put(src, 0, 4)
				.put(src, 8, 8);
		} catch (DecoderException e) {
			e.printStackTrace();
		}
    	return uuidBytes;
    }
    
    public static String toStringId(byte[] binId) {
    	byte[] uuidBytes = new byte[16];
    	String result = null;
    	ByteBuffer.wrap(uuidBytes)
			.put(binId, 4, 4)
			.put(binId, 2, 2)
			.put(binId, 0, 2)
			.put(binId, 8, 8);
		result = Hex.encodeHexString(uuidBytes);
    	return result;
    }
}

**However I got this class casting error when trying to retrieve data from database.**
2018-05-09T09:23:50,717 WARN  graphql.execution.SimpleDataFetcherExceptionHandler:23 - Exception while fetching data (/login) : java.lang.ClassCastException: java.lang.String cannot be cast to [B
java.util.concurrent.CompletionException: java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_66]
	at me.escoffier.vertx.completablefuture.VertxCompletableFuture.lambda$new$2(VertxCompletableFuture.java:70) ~[vertx-completable-future-0.1.1.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_66]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_66]
	at io.github.jklingsporn.vertx.jooq.completablefuture.async.AsyncCompletableFutureGenericQueryExecutor.lambda$executeAndClose$1(AsyncCompletableFutureGenericQueryExecutor.java:56) ~[vertx-jooq-completablefuture-async-4.0.0-BETA.jar:?]
	at io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl.lambda$handleAsyncQueryResultToResultSet$12(AsyncSQLConnectionImpl.java:306) ~[vertx-mysql-postgresql-client-3.5.1.jar:3.5.1]
	at io.vertx.ext.asyncsql.impl.ScalaUtils$3.apply(ScalaUtils.java:91) ~[vertx-mysql-postgresql-client-3.5.1.jar:3.5.1]
	at io.vertx.ext.asyncsql.impl.ScalaUtils$3.apply(ScalaUtils.java:87) ~[vertx-mysql-postgresql-client-3.5.1.jar:3.5.1]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library-2.12.4.jar:?]
	at io.vertx.ext.asyncsql.impl.VertxEventLoopExecutionContext.lambda$execute$0(VertxEventLoopExecutionContext.java:59) ~[vertx-mysql-postgresql-client-3.5.1.jar:3.5.1]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at com.ark.jooq.generate.UUIDConverter.from(UUIDConverter.java:9) ~[jooq-generate-1.0.jar:?]
	at io.github.jklingsporn.vertx.jooq.shared.async.AbstractAsyncQueryExecutor.lambda$convertFromSQL$2(AbstractAsyncQueryExecutor.java:55) ~[vertx-jooq-shared-async-4.0.0-BETA.jar:?]
	at java.util.function.Function.lambda$andThen$6(Function.java:88) ~[?:1.8.0_66]
	at io.github.jklingsporn.vertx.jooq.completablefuture.async.AsyncCompletableFutureQueryExecutor.lambda$findOne$1(AsyncCompletableFutureQueryExecutor.java:43) ~[vertx-jooq-completablefuture-async-4.0.0-BETA.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_66]
	... 21 more
2018-05-09T09:23:50,767 WARN  com.ark.server.LoggerHandlerImpl:162 - 0:0:0:0:0:0:0:1 -- "POST /graphql" 400 8871 154ms "http://localhost:8080/?query=mutation%20%7B%0A%20%20login(input%3A%20%7B%0A%20%20%20%20email%3A%20%22andy%22%2C%0A%20%20%20%20password%3A%20%22hope%20is%20a%20good%20thing%22%2C%0A%20%20%7D)%20%7B%0A%20%20%20%20userId%0A%20%20%20%20name%0A%20%20%20%20lastLogin%0A%20%20%20%20faceUrl%0A%20%20%20%20session%0A%20%20%20%20roles%0A%20%20%20%20createTime%0A%20%20%20%20updateTime%0A%20%20%7D%0A%7D" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
	{"query":"mutation {\n  login(input: {\n    email: \"andy\",\n    password: \"hope is a good thing\",\n  }) {\n    userId\n    name\n    lastLogin\n    faceUrl\n    session\n    roles\n    createTime\n    updateTime\n  }\n}","variables":null}

With a little debuging, I found out that the result from the data are Base64 encoded strings instead of byte[] the converter expects.
Could you help me with this issue?

Thank you!

**Comment by zeroc** [comment]
I think the problem was caused by JsonObject, which encodes byte[] into Base64 String automatically?
Can we somehow fix this problem?

**Comment by jklingsporn** [comment]
Interesting bug. I think the underlying problem here is, that the `AsyncSQLClient` does some conversion on it's own (`byte[]` into `String`), before the `Converter` does his work. I think we cannot easily intercept that process, so I think you have 4 options now:

1. Switch to the `-jdbc` version.
2. Change the `Converter` from `Converter<byte[], String>` to Converter<Object,Object>. You could then check the type in the conversion. Obviously, you're loosing typesafety here which is I can imagine is not desirable.
3. Customize `vertx-jooq` by overwriting the `AbstractAsyncQueryExecutor#convertFromSQL` method and perform some checks there.
4. Try the `-reactive` version of `vertx-jooq` which is part of the [4.0-BETA release](https://github.com/jklingsporn/vertx-jooq/releases/tag/4.0.0-BETA). The reactive driver has support for UUID datatype.

I know that none of the solutions is ideal, but for now, I cannot offer more.

**Comment by zeroc** [comment]
Hi,

Thank you for the solutions. 
So far I've tried solution 2 with no success, as JOOQ can't use Object DataType in createField for binary fields.
Solution 4 looks promising, I'll probably wait for it to support MySQL.
For now I'll just use string as UUID, the performance gain from binary primary ids probably doesn't justify the effort.
