### ISSUE TITLE
SQLite: Insert Return primary key always null

### ISSUE THREAD

**Issue by zero-88** [jklingsporn/vertx-jooq#70]
**Context**
- vertx 3.5.1
- jOOQ 3.10.6
- vertx-jooq-rx-jdbc 3.1.0
- vertx-jooq-generate 3.0.2
- sqlite-jdbc 3.23.1

**Log**
```
17:16:33.637 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : insert into tbl_x (key, a, b, c, d, e, f, g, h, k, l) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
17:16:33.639 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into tbl_x (key, a, b, c, d, e, f, g, h, k, l) values ('key', 'a', 'b', 'c', null, 'e', 'f', g', null, '', null)
17:16:33.661 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Affected row(s)          : 1
17:16:33.663 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : select last_insert_rowid()
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Fetched result           : +-------------------+
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |last_insert_rowid()|
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |                  0|
17:16:33.666 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +-------------------+
17:16:33.667 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Executing query          : select tbl_x.key from tbl_x where _rowid_ = ?
17:16:33.667 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : select tbl_x.key from tbl_x where _rowid_ = 0
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener - Fetched result           : +----------+
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : |key|
17:16:33.668 [vert.x-worker-thread-7] DEBUG org.jooq.tools.LoggerListener -                          : +----------+
17:16:33.673 [vert.x-eventloop-thread-1] ERROR com.myapp - Failed to startup application
java.lang.NullPointerException: Failed inserting record or no key
	at java.util.Objects.requireNonNull(Objects.java:290)
	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.lambda$insertReturningPrimary$3(AbstractVertxDAO.java:151)
	at io.github.jklingsporn.vertx.jooq.rx.jdbc.JDBCRXQueryExecutor.lambda$insertReturning$3(JDBCRXQueryExecutor.java:41)
```

**Comment by jklingsporn** [comment]
SQLite does not natively support the `INSERT ... RETURNING` syntax. Looking at your code, you are providing an id ('key') and thus it returns null.
> insert into tbl_x (key, a, b, c, d, e, f, g, h, k, l) values ('key', 'a', 'b', 'c', null, 'e', 'f', g', null, '', null)
It is debatable though if this method should throw an exception in case no key was generated or just return null for that key.

**Comment by jklingsporn** [comment]
I've filed an issue here: https://github.com/jOOQ/jOOQ/issues/7945

**Comment by jklingsporn** [comment]
@zero-88 can you please answer the question in the linked issue (https://github.com/jOOQ/jOOQ/issues/7945)?
