### ISSUE TITLE
Support jsonb with reactive driver

### ISSUE THREAD

**Issue by gofabian** [jklingsporn/vertx-jooq#81]
The json/jsonb support from #51 does not seem to work with the reactive Postgres driver. The problem is that the reactive driver creates instances of "Json" instead of "String".

Using the reactive driver: 
```
compile(group: 'io.github.jklingsporn', name: 'vertx-jooq-classic-reactive', version: '4.0.0')
```

I tried to write a new converter for this scenario:
```
public class JsonArrayConverter extends AbstractConverter<Object, JsonArray> {

    public JsonArrayConverter() {
        super(Object.class, JsonArray.class);
    }

    /**
     * Unwrap the JSON wrapper type (Postgres Reactive driver) and return the Vert.x JSON type.
     */
    @Override
    public JsonArray from(Object databaseJsonObject) {
        Json pgJsonWrapper = validateAndCast(databaseJsonObject, Json.class);
        return validateAndCast(pgJsonWrapper.value(), toType());
    }

    private <U> U validateAndCast(Object object, Class<U> type) {
        if (!type.isInstance(object)) {
            throw new IllegalArgumentException("Expected Vert.x JSON type: " + type + ", but got: " + object);
        }
        //noinspection unchecked
        return (U) object;
    }

    /**
     * Wrap the Vert.x JSON type into the JSON wrapper type (Postgres Reactive driver).
     */
    @Override
    public Object to(JsonArray vertxJsonObject) {
        return Json.create(vertxJsonObject);
    }

}
```

Activate the converter:
```
Database database = new Database();
database.setName(PostgresDatabase.class.getName());
// ...
database.setForcedTypes(List.of(
        new ForcedType()
                .withUserType(JsonArray.class.getName())
                .withConverter(JsonArrayConverter.class.getName())
                .withTypes("jsonb")
));
```

Actually reading data from the database works. But updating provokes this error:
```
org.jooq.exception.SQLDialectNotSupportedException: Type class io.reactiverse.pgclient.impl.data.JsonImpl is not supported in dialect POSTGRES
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:884)
	at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:823)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sqlCast(DefaultBinding.java:618)
	at org.jooq.impl.DefaultBinding$AbstractBinding.sql(DefaultBinding.java:707)
	at org.jooq.impl.Val.accept(Val.java:80)
...
```

What is wrong in my setup? Has anybody successfully used the combination of reactive and jsonb?

Thanks for your insights!

**Comment by sowmyark** [comment]
Were you able to solve this issue? Is there any workaround?

**Comment by gofabian** [comment]
The problem is that JOOQ depends on the declared `DataType` instances (see `SQLDataType`). 

The dirty solution is to create an instance of `DefaultDatatype` (e. g. as a static constant in your code) so that JOOQ knows it is able to handle instances of `JsonImpl`.

e. g. 

```
public static final DataType<JsonImpl> JSONB = new DefaultDataType<JsonImpl>(null, JsonImpl.class, "jsonb");
```

Remark: vertx-jooq is only able to convert from/to instances of JsonArray/JsonObject (e. g. like the JsonArrayConverter above). This is hard coded.

**Comment by sowmyark** [comment]
Thank you. Will try this out.
