### ISSUE TITLE
StringIndexOutOfBoundsException when generating DAO

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#89]
I've a custom generator strategy that extends `VertxGeneratorStrategy` and have over-ridden the `getJavaClassName()`. When generating DAO's, under this scenario, I get the following error:

```
[ERROR] Error while generating table DAO public.AccessToken
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at io.github.jklingsporn.vertx.jooq.generate.builder.VertxGeneratorBuilder$ExecutionStepImpl.lambda$withPostgresReactiveDriver$30(VertxGeneratorBuilder.java:411)
	at io.github.jklingsporn.vertx.jooq.generate.builder.ComponentBasedVertxGenerator.writeDAOConstructor(ComponentBasedVertxGenerator.java:83)
	at io.github.jklingsporn.vertx.jooq.generate.builder.DelegatingVertxGenerator.writeDAOConstructor(DelegatingVertxGenerator.java:64)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDAO(VertxGenerator.java:564)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDao(VertxGenerator.java:501)
	at org.jooq.codegen.JavaGenerator.generateDao(JavaGenerator.java:2867)
	at org.jooq.codegen.JavaGenerator.generateDaos(JavaGenerator.java:2854)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDaos(VertxGenerator.java:234)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:512)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:458)
	at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:380)
	at org.jooq.codegen.GenerationTool.run(GenerationTool.java:750)
	at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:220)
	at org.jooq.codegen.maven.Plugin.execute(Plugin.java:197)
```

**Diagnosis:**
Upon debugging, I notice that on [line 411](https://github.com/jklingsporn/vertx-jooq/blob/e1e6cdcbad523b21ae9f9904f672a65a0f909448/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/builder/VertxGeneratorBuilder.java#L411) in `VertxGeneratorBuilder.java`, the code is expecting a fully qualified class name. However, the calling code in `VertxGenerator.java`, [line 512](https://github.com/jklingsporn/vertx-jooq/blob/e1e6cdcbad523b21ae9f9904f672a65a0f909448/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/VertxGenerator.java#L512) strips the package name because of the call to `out.ref(...)`.

**Recommended fix:**
Remove the call to `out.fix(...)` so that the code in `VertxGenerator.java`, looks like this.

`String pType = getStrategy().getFullJavaClassName(table, GeneratorStrategy.Mode.POJO);`

**Comment by jklingsporn** [comment]
Hello and thank you for your bug report. I've checked the code in `out.ref(...)` and it basically returns what you put in there. So your suggested fix wouldn't help. 
I agree however, that it is unlucky that even though you are allowed to overwrite `getFullJavaClassName()` it has to follow the convention `somePackage.ClassName`. `getFullJavaClassName()` internally calls `getJavaPackageName(...)` so it assumes that POJOs are put into `pojos.MyPojo`, records into `records.MyRecord` etc. 
Can you tell me what you want to achieve so I can maybe help with another solution?

**Comment by paninics** [comment]
Because of internal conventions, I'm trying to have a different naming convention and package structure than the default. Hence I started overriding the `getJavaClassName()`, `getJavaPackageName()` etc. in my custom strategy which extends `VertxGeneratorStrategy`. However, I always run into one issue or the other because the code is making some assumptions regarding naming conventions / package structure and often those are hard coded. The easiest way for you to look at this issue is assume you need the following package hierarchy:

`com.xyz.db.tables` - to contain all Tables
`com.xyz.db.tables.pojos` - to contain all POJOs
`com.xyz.db.tables.daos` - to contain all DAOs 

And similarly for `mappers` and `records` as well. If you're able to get this working, then tweak it to have a flatter structure and singular naming convention as shown below - which is what is my true requirement. 

`com.xyz.db.table`
`com.xyz.db.pojo`
`com.xyz.db.dao`
